#takes the json file imported or generated by other loaders and returns python objects

import json

def load_file(path):
    with open(path, "r") as file:
        data = json.load(file)
    sections = list(data.get("lattices",{}).keys())
    metadata = data.get("parameters", {})
    metadata["name"] = data.get("title")
    elements = build_element_objects(data.get("elements"), data.get("lattices"))
    return sections,metadata, elements

def build_element_objects(elements, lattices):
    pass
