#takes the json file imported or generated by other loaders and returns python objects
from file_io.elegant_loader import load_elegant
from file_io.opa_loader import load_opa
from file_io.madx_loader import load_madx
from file_io.elegant_loader import load_elegant
import json

def load_file(path):
    with open(path, "r") as file:
        #seperat loading and returning json depending on file type

        data = json.load(file)
    sections = list(data.get("lattices",{}).keys())
    metadata = data.get("parameters", {})
    metadata["name"] = data.get("title")
    elements = build_element_objects(data.get("elements"), data.get("lattices"))
    return sections,metadata, elements

def build_element_objects(elements, lattices):
    pass
